---
- hosts: leader
  become: yes
  tasks:
    - name: add public keys
      ansible.posix.authorized_key:
        user: ilham-leader
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
