---
- hosts: gateway
  become: true
  gather_facts: false
  tasks:

    - name: Create User
      user:
        name: "{{username}}"
        state: present
        shell: /bin/bash
        password: "{{password}}"
        #update_password: on_create
        groups: sudo
        append: yes
        create_home: true
        home: /home/{{username}}

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
    #- authorized_key:
        #user: {{username}}
        user: ilham3
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    #- name: "Deploy SSH Public Key"
      #ansible.posix.authorized_key:
        #user: "{{ username }}"
        #state: present
        #key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
  vars:
  # Define your username and password here that you want to create on target hosts.
    username: "ilham3"
    password: "$5$QlVlvCsU$IZT6/EX1oNw/5MwbG.qSFx9elR4KozdbCQD8KYmXMl3"
