- hosts: gateway
  become: true
  tasks:

# Install Docker
#--
#

  - name: "update & upgrade system"
    apt:
      update_cache: yes
      upgrade: dist
  
  - name: "install prerequisite"
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

  - name: "add GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: "set up repository"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: "update system"
    apt:
      update_cache: yes

  - name: "Install Docker Engine, containerd, and Docker Compose"
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

  - name: add user permissions
    shell: "sudo usermod -aG docker {{user}}"

  # Installs Docker SDK
  # --
  # 
  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{user}}"
    pip:
      name:
        - docker
        - docker-compose

  vars:
    user: "ilham-gateway"
